Bloggie/Pages/Admin/Blogs/Add.cshtml.cs
using Bloggie.Data;
using Bloggie.Models.Domain;
using Bloggie.Models.ViewModels;
using Bloggie.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace Bloggie.Pages.Admin.Blogs
{
    public class AddModel : PageModel
    {
        public readonly IBlogPostRepository blogPostRepository;
        
        [BindProperty]
        public AddBlogPost AddBlogPostRequest { get; set; }

        [BindProperty]
        public string tags { get; set; }



        public AddModel(IBlogPostRepository _blogPostRepository)
        {
            this.blogPostRepository = _blogPostRepository;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            var blogPost = new BlogPost()
            {
                Heading = AddBlogPostRequest.Heading,
                PageTitle = AddBlogPostRequest.PageTitle,
                Content = AddBlogPostRequest.Content,
                ShortDescription = AddBlogPostRequest.ShortDescription,
                FeaturedImageUrl = AddBlogPostRequest.FeaturedImageUrl,
                UrlHandle = AddBlogPostRequest.UrlHandle,
                PublishDate = AddBlogPostRequest.PublishDate,
                Author = AddBlogPostRequest.Author,
                Visible = AddBlogPostRequest.Visible,
                tags = new List<Tag>(
                    this.tags.Split(',')
                        .Select(x => new Tag() { 
                            Name = x.Trim()
                        }
                    )
                )
            };

            await this.blogPostRepository.AddAsync(blogPost);

            Notification notification = new Notification
            {
                type = Enum.NotificationType.Sucess,
                message = "New blog created!"
            };

            TempData["Notification"] = JsonSerializer.Serialize(notification);

            return RedirectToPage("/Admin/Blogs/List");
        }
    }
}

Bloggie/Pages/Admin/Blogs/Edit.cshtml.cs
using Bloggie.Data;
using Bloggie.Enum;
using Bloggie.Models.Domain;
using Bloggie.Models.ViewModels;
using Bloggie.Repositories;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace Bloggie.Pages.Admin.Blogs
{
    public class EditModel : PageModel
    {
        private readonly IBlogPostRepository blogPostRepository;

        [BindProperty]
        public BlogPost blogPost { get; set; }

        [BindProperty]
        public string tags { get; set; }

        public EditModel(IBlogPostRepository _blogPostRepository)
        {
            this.blogPostRepository = _blogPostRepository;
        }

        public async Task OnGet(Guid id)
        {
            blogPost = await this.blogPostRepository.GetAsync(id);

            if (blogPost.tags != null && blogPost.tags != null)
            {
                tags = string.Join(',', blogPost.tags.Select(x => x.Name));
            }
        }

        public async Task<IActionResult> OnPostEdit()
        {
            try
            {
                blogPost.tags = new List<Tag>(tags.Split(',')
                                    .Select(x => new Tag() { Name = x.Trim() }));

                await this.blogPostRepository.UpdateAsync(blogPost);

                ViewData["MessageDescription"] = "Save was successfully saved!";

                ViewData["Notification"] = new Notification()
                {
                    message = "Record updated successfully",
                    type = NotificationType.Sucess
                };
            }
            catch (Exception)
            {
                ViewData["Notification"] = new Notification()
                {
                    message = "Something went wrong!",
                    type = NotificationType.Error
                };
            }

            return Page();

        }

        public async Task<IActionResult> OnPostDelete()
        {
            Boolean isDeleted = await this.blogPostRepository.DeleteAsync(blogPost.Id);

            if (isDeleted)
            {
                Notification notification = new Notification
                {
                    type = Enum.NotificationType.Sucess,
                    message = "Blog deleted successfully!"
                };

                TempData["Notification"] = JsonSerializer.Serialize(notification);

                return RedirectToPage("/Admin/Blogs/List");
            }

            return Page();
        }
    }
}

Bloggie/Pages/Admin/Blogs/List.cshtml.cs
using Bloggie.Data;
using Bloggie.Models.Domain;
using Bloggie.Models.ViewModels;
using Bloggie.Repositories;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace Bloggie.Pages.Admin.Blogs
{
    public class ListModel : PageModel
    {
        private readonly IBlogPostRepository blogPostRepository;

        public List<BlogPost> blogPosts { get; set; }

        public ListModel(IBlogPostRepository _blogPostRepository)
        {
            this.blogPostRepository = _blogPostRepository;
        }

        public async Task OnGet()
        {
            string notificationJson = (string)TempData["Notification"];

            if(!string.IsNullOrEmpty(notificationJson))
            {
                ViewData["Notification"] = JsonSerializer.Deserialize<Notification>(notificationJson);
            }

            blogPosts = (await this.blogPostRepository.GetAllAsync())?.ToList();
        }
    }
}

Bloggie/Pages/Blog/Details.cshtml.cs
using Bloggie.Models.Domain;
using Bloggie.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bloggie.Pages.Blogs
{
    public class DetailsModel : PageModel
    {
        private readonly IBlogPostRepository blogPostRepository;
        public BlogPost blogPost { get; set; }

        public DetailsModel(IBlogPostRepository _blogPostRepository)
        {
            this.blogPostRepository = _blogPostRepository;
        }
        public async Task<IActionResult> OnGet(string urlHandle)
        {
            blogPost = await this.blogPostRepository.GetAsyncByUrlHandle(urlHandle);
            return Page();
        }
    }
}

Bloggie/Pages/Admin/Blogs/Add.cshtml
@page
@model Bloggie.Pages.Admin.Blogs.AddModel
@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Add Blog Post</h1>
    </div>
</div>

<div>
    <div class="container">
        <form method="post">
            <div class="mb-3">
                <label for="heading" class="form-label">Heading</label>
                <input type="text" class="form-control" id="heading" asp-for="AddBlogPostRequest.Heading">
            </div>

            <div class="mb-3">
                <label for="pageTitle" class="form-label">Page Title</label>
                <input type="text" class="form-control" id="pageTitle" asp-for="AddBlogPostRequest.PageTitle">
            </div>

            <div class="mb-3">
                <label for="content" class="form-label">Content</label>
                <textarea class="form-control" id="content" asp-for="AddBlogPostRequest.Content"></textarea>
            </div>

            <div class="mb-3">
                <label for="shortDescription" class="form-label">Short Description</label>
                <input type="text" class="form-control" id="shortDescription" asp-for="AddBlogPostRequest.ShortDescription">
            </div>

            <div class="mb-3">
                <label for="featuredImageUrl" class="form-label">Featured Image URL</label>
                <input type="text" class="form-control" id="featuredImageUrl" asp-for="AddBlogPostRequest.FeaturedImageUrl">
            </div>

            <div class="mb-3">
                <label for="urlHandle" class="form-label">URL Handle</label>
                <input type="text" class="form-control" id="urlHandle" asp-for="AddBlogPostRequest.UrlHandle">
            </div>

            <div class="mb-3">
                <label for="publishDate" class="form-label">Publish Date</label>
                <input type="date" class="form-control" id="publishDate" asp-for="AddBlogPostRequest.PublishDate">
            </div>

            <div class="mb-3">
                <label for="author" class="form-label">Author</label>
                <input type="text" class="form-control" id="author" asp-for="AddBlogPostRequest.Author">
            </div>

            <div class="mb-3">
                <label for="" class="form-label">Tags (comma separated)</label>
                <input type="text" class="form-control" id="tags" asp-for="tags">
            </div>

            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="isVisible" asp-for="AddBlogPostRequest.Visible">
                <label class="form-check-label" for="isVisible">
                    Is Visible
                </label>
            </div>

            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        const editor = new FroalaEditor('#content');
    </script>
}

Bloggie/Pages/Admin/Blogs/Edit.cshtml
@page "{id:Guid}"
@model Bloggie.Pages.Admin.Blogs.EditModel
@{
}

    <div class="bg-secondary bg-opacity-10 py-2 mb-5">
        <div class="container">
            <h1>Edit Blog Post</h1>
        </div>
    </div>

    <partial name="_Notification">

    @if(Model.blogPost != null)
    {
        <div>
            <div class="container">
                <form method="post">
                    <div class="mb-3">
                        <label for="id" class="form-label">Id</label>
                        <input type="text" class="form-control" id="id" asp-for="blogPost.Id" readonly>
                    </div>

                    <div class="mb-3">
                        <label for="heading" class="form-label">Heading</label>
                        <input type="text" class="form-control" id="heading" asp-for="blogPost.Heading">
                    </div>

                    <div class="mb-3">
                        <label for="pageTitle" class="form-label">Page Title</label>
                        <input type="text" class="form-control" id="pageTitle" asp-for="blogPost.PageTitle">
                    </div>

                    <div class="mb-3">
                        <label for="content" class="form-label">Content</label>
                        <textarea class="form-control" id="content" asp-for="blogPost.Content"></textarea>
                    </div>

                    <div class="mb-3">
                        <label for="shortDescription" class="form-label">Short Description</label>
                        <input type="text" class="form-control" id="shortDescription" asp-for="blogPost.ShortDescription">
                    </div>

                    <div class="mb-3">
                        <label for="featuredImageUrl" class="form-label">Featured Image URL</label>
                        <input type="text" class="form-control" id="featuredImageUrl" asp-for="blogPost.FeaturedImageUrl">
                    </div>

                    <div class="mb-3">
                        <label for="urlHandle" class="form-label">URL Handle</label>
                        <input type="text" class="form-control" id="urlHandle" asp-for="blogPost.UrlHandle">
                    </div>

                    <div class="mb-3">
                        <label for="publishDate" class="form-label">Publish Date</label>
                        <input type="date" class="form-control" id="publishDate" asp-for="blogPost.PublishDate">
                    </div>

                    <div class="mb-3">
                        <label for="author" class="form-label">Author</label>
                        <input type="text" class="form-control" id="author" asp-for="blogPost.Author">
                    </div>

                    <div class="mb-3">
                        <label for="" class="form-label">Tags (comma separated)</label>
                        <input type="text" class="form-control" id="tags" asp-for="tags">
                    </div>

                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" id="isVisible" asp-for="blogPost.Visible">
                        <label class="form-check-label" for="isVisible">
                            Is Visible
                        </label>
                    </div>

                    <div class="mb-3 d-flex justify-content-between">
                        <button class="btn btn-primary" type="submit" asp-page-handler="Edit">Submit</button>
                        <button class="btn btn-danger" type="submit" asp-page-handler="Delete">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    } else {
        <div>
            <div class="container">
                Blog Not Found!
            </div>
        </div>
    }


    @section Scripts {
        <script>
            const editor = new FroalaEditor('#content');
        </script>
    }

Bloggie/Pages/Admin/Blogs/List.cshtml
@page
@model Bloggie.Pages.Admin.Blogs.ListModel
@{
}


<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>List Blog Post</h1>
    </div>
</div>

<partial name="_Notification"></partial>

@if(Model.blogPosts != null && Model.blogPosts.Any())
{
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Heading</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var blogPost in Model.blogPosts)
                {
                    <tr>
                        <td>@blogPost.Id</td>
                        <td>@blogPost.Heading</td>
                        <td><a href="/Admin/Blogs/Edit/@blogPost.Id">View</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
} else
{
    <div class="container">
        <p>No blogs posts were found!</p>
    </div>
}